version: '3'

services:
  hardhat:
    build:
      context: hardhat
      dockerfile: Dockerfile
    volumes:
      - ./hardhat:/app
      - hardhat-node-modules:/app/node_modules
    tty: true
    ports:
      - "8545:8545"
    command: |
      sh -c "npm run dev"

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  chain-data:
  db-data:
  hardhat-node-modules:
    driver_opts:
      type: none
      device: $PWD/hardhat/node_modules
      o: bind
  web-node-modules:
    driver_opts:
      type: none
      device: $PWD/web/node_modules
      o: bind
