version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - ethereum

  ethereum:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: 'npm run hardhat-node'
    ports:
      - "8545:8545"
