version: '3'

services:
  hardhat:
    build:
      context: hardhat
      dockerfile: Dockerfile
    volumes:
      - ./hardhat:/app
      - hardhat-node_modules:/app/node_modules
    tty: true
    ports:
      - "8545:8545"
    command: |
      sh -c "npm run dev"

  web:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web:/app
      - web-node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: |
      sh -c "npm run dev"
    restart: always
    tty: true
    stdin_open: true

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  chain-data:
  db-data:
  hardhat-node_modules:
  web-node_modules:
