-- AlterTable
ALTER TABLE "ScoreReport" ALTER COLUMN "scoreCO2Reduction" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "scoreCarbonEfficiency" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalScore" SET DATA TYPE DOUBLE PRECISION;
